// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include "../inst/include/XOMultinom.h"
#include <RcppArmadillo.h>
#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// prob_max_leq
double prob_max_leq(int n, const std::vector<double>& pi, double c);
RcppExport SEXP _XOMultinom_prob_max_leq(SEXP nSEXP, SEXP piSEXP, SEXP cSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< int >::type n(nSEXP);
    Rcpp::traits::input_parameter< const std::vector<double>& >::type pi(piSEXP);
    Rcpp::traits::input_parameter< double >::type c(cSEXP);
    rcpp_result_gen = Rcpp::wrap(prob_max_leq(n, pi, c));
    return rcpp_result_gen;
END_RCPP
}
// prob_min_geq
double prob_min_geq(int n, const std::vector<double>& pi, double c);
RcppExport SEXP _XOMultinom_prob_min_geq(SEXP nSEXP, SEXP piSEXP, SEXP cSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< int >::type n(nSEXP);
    Rcpp::traits::input_parameter< const std::vector<double>& >::type pi(piSEXP);
    Rcpp::traits::input_parameter< double >::type c(cSEXP);
    rcpp_result_gen = Rcpp::wrap(prob_min_geq(n, pi, c));
    return rcpp_result_gen;
END_RCPP
}
// prob_max_gt
double prob_max_gt(int n, const std::vector<double>& pi, double c);
RcppExport SEXP _XOMultinom_prob_max_gt(SEXP nSEXP, SEXP piSEXP, SEXP cSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< int >::type n(nSEXP);
    Rcpp::traits::input_parameter< const std::vector<double>& >::type pi(piSEXP);
    Rcpp::traits::input_parameter< double >::type c(cSEXP);
    rcpp_result_gen = Rcpp::wrap(prob_max_gt(n, pi, c));
    return rcpp_result_gen;
END_RCPP
}
// prob_min_lt
double prob_min_lt(int n, const std::vector<double>& pi, double c);
RcppExport SEXP _XOMultinom_prob_min_lt(SEXP nSEXP, SEXP piSEXP, SEXP cSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< int >::type n(nSEXP);
    Rcpp::traits::input_parameter< const std::vector<double>& >::type pi(piSEXP);
    Rcpp::traits::input_parameter< double >::type c(cSEXP);
    rcpp_result_gen = Rcpp::wrap(prob_min_lt(n, pi, c));
    return rcpp_result_gen;
END_RCPP
}
// prob_min_leq
double prob_min_leq(int n, const std::vector<double>& pi, double c);
RcppExport SEXP _XOMultinom_prob_min_leq(SEXP nSEXP, SEXP piSEXP, SEXP cSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< int >::type n(nSEXP);
    Rcpp::traits::input_parameter< const std::vector<double>& >::type pi(piSEXP);
    Rcpp::traits::input_parameter< double >::type c(cSEXP);
    rcpp_result_gen = Rcpp::wrap(prob_min_leq(n, pi, c));
    return rcpp_result_gen;
END_RCPP
}
// prob_joint
double prob_joint(int n, const std::vector<double>& pi, double a, double b);
RcppExport SEXP _XOMultinom_prob_joint(SEXP nSEXP, SEXP piSEXP, SEXP aSEXP, SEXP bSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< int >::type n(nSEXP);
    Rcpp::traits::input_parameter< const std::vector<double>& >::type pi(piSEXP);
    Rcpp::traits::input_parameter< double >::type a(aSEXP);
    Rcpp::traits::input_parameter< double >::type b(bSEXP);
    rcpp_result_gen = Rcpp::wrap(prob_joint(n, pi, a, b));
    return rcpp_result_gen;
END_RCPP
}
// prob_max_eq
double prob_max_eq(int n, const std::vector<double>& pi, double c);
RcppExport SEXP _XOMultinom_prob_max_eq(SEXP nSEXP, SEXP piSEXP, SEXP cSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< int >::type n(nSEXP);
    Rcpp::traits::input_parameter< const std::vector<double>& >::type pi(piSEXP);
    Rcpp::traits::input_parameter< double >::type c(cSEXP);
    rcpp_result_gen = Rcpp::wrap(prob_max_eq(n, pi, c));
    return rcpp_result_gen;
END_RCPP
}
// prob_min_eq
double prob_min_eq(int n, const std::vector<double>& pi, double c);
RcppExport SEXP _XOMultinom_prob_min_eq(SEXP nSEXP, SEXP piSEXP, SEXP cSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< int >::type n(nSEXP);
    Rcpp::traits::input_parameter< const std::vector<double>& >::type pi(piSEXP);
    Rcpp::traits::input_parameter< double >::type c(cSEXP);
    rcpp_result_gen = Rcpp::wrap(prob_min_eq(n, pi, c));
    return rcpp_result_gen;
END_RCPP
}
// pmf_max_range
Rcpp::NumericVector pmf_max_range(int n, const std::vector<double>& pi, double c_lo, double c_hi);
RcppExport SEXP _XOMultinom_pmf_max_range(SEXP nSEXP, SEXP piSEXP, SEXP c_loSEXP, SEXP c_hiSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< int >::type n(nSEXP);
    Rcpp::traits::input_parameter< const std::vector<double>& >::type pi(piSEXP);
    Rcpp::traits::input_parameter< double >::type c_lo(c_loSEXP);
    Rcpp::traits::input_parameter< double >::type c_hi(c_hiSEXP);
    rcpp_result_gen = Rcpp::wrap(pmf_max_range(n, pi, c_lo, c_hi));
    return rcpp_result_gen;
END_RCPP
}
// pmf_min_range
Rcpp::NumericVector pmf_min_range(int n, const std::vector<double>& pi, double c_lo, double c_hi);
RcppExport SEXP _XOMultinom_pmf_min_range(SEXP nSEXP, SEXP piSEXP, SEXP c_loSEXP, SEXP c_hiSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< int >::type n(nSEXP);
    Rcpp::traits::input_parameter< const std::vector<double>& >::type pi(piSEXP);
    Rcpp::traits::input_parameter< double >::type c_lo(c_loSEXP);
    Rcpp::traits::input_parameter< double >::type c_hi(c_hiSEXP);
    rcpp_result_gen = Rcpp::wrap(pmf_min_range(n, pi, c_lo, c_hi));
    return rcpp_result_gen;
END_RCPP
}
// prob_range_lt
double prob_range_lt(int n, const std::vector<double>& pi, double r);
RcppExport SEXP _XOMultinom_prob_range_lt(SEXP nSEXP, SEXP piSEXP, SEXP rSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< int >::type n(nSEXP);
    Rcpp::traits::input_parameter< const std::vector<double>& >::type pi(piSEXP);
    Rcpp::traits::input_parameter< double >::type r(rSEXP);
    rcpp_result_gen = Rcpp::wrap(prob_range_lt(n, pi, r));
    return rcpp_result_gen;
END_RCPP
}
// prob_range_leq
double prob_range_leq(int n, const std::vector<double>& pi, double r);
RcppExport SEXP _XOMultinom_prob_range_leq(SEXP nSEXP, SEXP piSEXP, SEXP rSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< int >::type n(nSEXP);
    Rcpp::traits::input_parameter< const std::vector<double>& >::type pi(piSEXP);
    Rcpp::traits::input_parameter< double >::type r(rSEXP);
    rcpp_result_gen = Rcpp::wrap(prob_range_leq(n, pi, r));
    return rcpp_result_gen;
END_RCPP
}
// prob_range_geq
double prob_range_geq(int n, const std::vector<double>& pi, double r);
RcppExport SEXP _XOMultinom_prob_range_geq(SEXP nSEXP, SEXP piSEXP, SEXP rSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< int >::type n(nSEXP);
    Rcpp::traits::input_parameter< const std::vector<double>& >::type pi(piSEXP);
    Rcpp::traits::input_parameter< double >::type r(rSEXP);
    rcpp_result_gen = Rcpp::wrap(prob_range_geq(n, pi, r));
    return rcpp_result_gen;
END_RCPP
}
// prob_range_gt
double prob_range_gt(int n, const std::vector<double>& pi, double r);
RcppExport SEXP _XOMultinom_prob_range_gt(SEXP nSEXP, SEXP piSEXP, SEXP rSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< int >::type n(nSEXP);
    Rcpp::traits::input_parameter< const std::vector<double>& >::type pi(piSEXP);
    Rcpp::traits::input_parameter< double >::type r(rSEXP);
    rcpp_result_gen = Rcpp::wrap(prob_range_gt(n, pi, r));
    return rcpp_result_gen;
END_RCPP
}
// prob_range_eq
double prob_range_eq(int n, const std::vector<double>& pi, double r);
RcppExport SEXP _XOMultinom_prob_range_eq(SEXP nSEXP, SEXP piSEXP, SEXP rSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< int >::type n(nSEXP);
    Rcpp::traits::input_parameter< const std::vector<double>& >::type pi(piSEXP);
    Rcpp::traits::input_parameter< double >::type r(rSEXP);
    rcpp_result_gen = Rcpp::wrap(prob_range_eq(n, pi, r));
    return rcpp_result_gen;
END_RCPP
}
// pmf_range_range
Rcpp::NumericVector pmf_range_range(int n, const std::vector<double>& pi, double r_lo, double r_hi);
RcppExport SEXP _XOMultinom_pmf_range_range(SEXP nSEXP, SEXP piSEXP, SEXP r_loSEXP, SEXP r_hiSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< int >::type n(nSEXP);
    Rcpp::traits::input_parameter< const std::vector<double>& >::type pi(piSEXP);
    Rcpp::traits::input_parameter< double >::type r_lo(r_loSEXP);
    Rcpp::traits::input_parameter< double >::type r_hi(r_hiSEXP);
    rcpp_result_gen = Rcpp::wrap(pmf_range_range(n, pi, r_lo, r_hi));
    return rcpp_result_gen;
END_RCPP
}
// dmaxmultinom_corrado
Rcpp::NumericVector dmaxmultinom_corrado(const Rcpp::NumericVector& x, const int& size, const Rcpp::NumericVector& prob, const bool& logd, const bool& verbose);
RcppExport SEXP _XOMultinom_dmaxmultinom_corrado(SEXP xSEXP, SEXP sizeSEXP, SEXP probSEXP, SEXP logdSEXP, SEXP verboseSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const Rcpp::NumericVector& >::type x(xSEXP);
    Rcpp::traits::input_parameter< const int& >::type size(sizeSEXP);
    Rcpp::traits::input_parameter< const Rcpp::NumericVector& >::type prob(probSEXP);
    Rcpp::traits::input_parameter< const bool& >::type logd(logdSEXP);
    Rcpp::traits::input_parameter< const bool& >::type verbose(verboseSEXP);
    rcpp_result_gen = Rcpp::wrap(dmaxmultinom_corrado(x, size, prob, logd, verbose));
    return rcpp_result_gen;
END_RCPP
}
// dminmultinom_corrado
Rcpp::NumericVector dminmultinom_corrado(const Rcpp::NumericVector& x, const int& size, const Rcpp::NumericVector& prob, const bool& logd, const bool& verbose);
RcppExport SEXP _XOMultinom_dminmultinom_corrado(SEXP xSEXP, SEXP sizeSEXP, SEXP probSEXP, SEXP logdSEXP, SEXP verboseSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const Rcpp::NumericVector& >::type x(xSEXP);
    Rcpp::traits::input_parameter< const int& >::type size(sizeSEXP);
    Rcpp::traits::input_parameter< const Rcpp::NumericVector& >::type prob(probSEXP);
    Rcpp::traits::input_parameter< const bool& >::type logd(logdSEXP);
    Rcpp::traits::input_parameter< const bool& >::type verbose(verboseSEXP);
    rcpp_result_gen = Rcpp::wrap(dminmultinom_corrado(x, size, prob, logd, verbose));
    return rcpp_result_gen;
END_RCPP
}
// drangemultinom_corrado
Rcpp::NumericVector drangemultinom_corrado(const Rcpp::NumericVector& x, const int& size, const Rcpp::NumericVector& prob, const bool& logd, const bool& verbose);
RcppExport SEXP _XOMultinom_drangemultinom_corrado(SEXP xSEXP, SEXP sizeSEXP, SEXP probSEXP, SEXP logdSEXP, SEXP verboseSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const Rcpp::NumericVector& >::type x(xSEXP);
    Rcpp::traits::input_parameter< const int& >::type size(sizeSEXP);
    Rcpp::traits::input_parameter< const Rcpp::NumericVector& >::type prob(probSEXP);
    Rcpp::traits::input_parameter< const bool& >::type logd(logdSEXP);
    Rcpp::traits::input_parameter< const bool& >::type verbose(verboseSEXP);
    rcpp_result_gen = Rcpp::wrap(drangemultinom_corrado(x, size, prob, logd, verbose));
    return rcpp_result_gen;
END_RCPP
}
// highest_order_statistics
double highest_order_statistics(const double& td, int n, int m, int J);
RcppExport SEXP _XOMultinom_highest_order_statistics(SEXP tdSEXP, SEXP nSEXP, SEXP mSEXP, SEXP JSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const double& >::type td(tdSEXP);
    Rcpp::traits::input_parameter< int >::type n(nSEXP);
    Rcpp::traits::input_parameter< int >::type m(mSEXP);
    Rcpp::traits::input_parameter< int >::type J(JSEXP);
    rcpp_result_gen = Rcpp::wrap(highest_order_statistics(td, n, m, J));
    return rcpp_result_gen;
END_RCPP
}
// max_order_statistic
double max_order_statistic(const double& td, int n, int m);
RcppExport SEXP _XOMultinom_max_order_statistic(SEXP tdSEXP, SEXP nSEXP, SEXP mSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const double& >::type td(tdSEXP);
    Rcpp::traits::input_parameter< int >::type n(nSEXP);
    Rcpp::traits::input_parameter< int >::type m(mSEXP);
    rcpp_result_gen = Rcpp::wrap(max_order_statistic(td, n, m));
    return rcpp_result_gen;
END_RCPP
}
// pmaxmultinom_corrado
Rcpp::NumericVector pmaxmultinom_corrado(const Rcpp::NumericVector& x, const int& size, const Rcpp::NumericVector& prob, const bool& logd, const bool& verbose);
RcppExport SEXP _XOMultinom_pmaxmultinom_corrado(SEXP xSEXP, SEXP sizeSEXP, SEXP probSEXP, SEXP logdSEXP, SEXP verboseSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const Rcpp::NumericVector& >::type x(xSEXP);
    Rcpp::traits::input_parameter< const int& >::type size(sizeSEXP);
    Rcpp::traits::input_parameter< const Rcpp::NumericVector& >::type prob(probSEXP);
    Rcpp::traits::input_parameter< const bool& >::type logd(logdSEXP);
    Rcpp::traits::input_parameter< const bool& >::type verbose(verboseSEXP);
    rcpp_result_gen = Rcpp::wrap(pmaxmultinom_corrado(x, size, prob, logd, verbose));
    return rcpp_result_gen;
END_RCPP
}
// pminmultinom_corrado
Rcpp::NumericVector pminmultinom_corrado(const Rcpp::NumericVector& x, const int& size, const Rcpp::NumericVector& prob, const bool& logd, const bool& verbose);
RcppExport SEXP _XOMultinom_pminmultinom_corrado(SEXP xSEXP, SEXP sizeSEXP, SEXP probSEXP, SEXP logdSEXP, SEXP verboseSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const Rcpp::NumericVector& >::type x(xSEXP);
    Rcpp::traits::input_parameter< const int& >::type size(sizeSEXP);
    Rcpp::traits::input_parameter< const Rcpp::NumericVector& >::type prob(probSEXP);
    Rcpp::traits::input_parameter< const bool& >::type logd(logdSEXP);
    Rcpp::traits::input_parameter< const bool& >::type verbose(verboseSEXP);
    rcpp_result_gen = Rcpp::wrap(pminmultinom_corrado(x, size, prob, logd, verbose));
    return rcpp_result_gen;
END_RCPP
}
// prangemultinom_corrado
Rcpp::NumericVector prangemultinom_corrado(const Rcpp::NumericVector& x, const int& size, const Rcpp::NumericVector& prob, const bool& logd, const bool& verbose);
RcppExport SEXP _XOMultinom_prangemultinom_corrado(SEXP xSEXP, SEXP sizeSEXP, SEXP probSEXP, SEXP logdSEXP, SEXP verboseSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const Rcpp::NumericVector& >::type x(xSEXP);
    Rcpp::traits::input_parameter< const int& >::type size(sizeSEXP);
    Rcpp::traits::input_parameter< const Rcpp::NumericVector& >::type prob(probSEXP);
    Rcpp::traits::input_parameter< const bool& >::type logd(logdSEXP);
    Rcpp::traits::input_parameter< const bool& >::type verbose(verboseSEXP);
    rcpp_result_gen = Rcpp::wrap(prangemultinom_corrado(x, size, prob, logd, verbose));
    return rcpp_result_gen;
END_RCPP
}
// range_probability
double range_probability(const double& td, int n, int m);
RcppExport SEXP _XOMultinom_range_probability(SEXP tdSEXP, SEXP nSEXP, SEXP mSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const double& >::type td(tdSEXP);
    Rcpp::traits::input_parameter< int >::type n(nSEXP);
    Rcpp::traits::input_parameter< int >::type m(mSEXP);
    rcpp_result_gen = Rcpp::wrap(range_probability(td, n, m));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_XOMultinom_prob_max_leq", (DL_FUNC) &_XOMultinom_prob_max_leq, 3},
    {"_XOMultinom_prob_min_geq", (DL_FUNC) &_XOMultinom_prob_min_geq, 3},
    {"_XOMultinom_prob_max_gt", (DL_FUNC) &_XOMultinom_prob_max_gt, 3},
    {"_XOMultinom_prob_min_lt", (DL_FUNC) &_XOMultinom_prob_min_lt, 3},
    {"_XOMultinom_prob_min_leq", (DL_FUNC) &_XOMultinom_prob_min_leq, 3},
    {"_XOMultinom_prob_joint", (DL_FUNC) &_XOMultinom_prob_joint, 4},
    {"_XOMultinom_prob_max_eq", (DL_FUNC) &_XOMultinom_prob_max_eq, 3},
    {"_XOMultinom_prob_min_eq", (DL_FUNC) &_XOMultinom_prob_min_eq, 3},
    {"_XOMultinom_pmf_max_range", (DL_FUNC) &_XOMultinom_pmf_max_range, 4},
    {"_XOMultinom_pmf_min_range", (DL_FUNC) &_XOMultinom_pmf_min_range, 4},
    {"_XOMultinom_prob_range_lt", (DL_FUNC) &_XOMultinom_prob_range_lt, 3},
    {"_XOMultinom_prob_range_leq", (DL_FUNC) &_XOMultinom_prob_range_leq, 3},
    {"_XOMultinom_prob_range_geq", (DL_FUNC) &_XOMultinom_prob_range_geq, 3},
    {"_XOMultinom_prob_range_gt", (DL_FUNC) &_XOMultinom_prob_range_gt, 3},
    {"_XOMultinom_prob_range_eq", (DL_FUNC) &_XOMultinom_prob_range_eq, 3},
    {"_XOMultinom_pmf_range_range", (DL_FUNC) &_XOMultinom_pmf_range_range, 4},
    {"_XOMultinom_dmaxmultinom_corrado", (DL_FUNC) &_XOMultinom_dmaxmultinom_corrado, 5},
    {"_XOMultinom_dminmultinom_corrado", (DL_FUNC) &_XOMultinom_dminmultinom_corrado, 5},
    {"_XOMultinom_drangemultinom_corrado", (DL_FUNC) &_XOMultinom_drangemultinom_corrado, 5},
    {"_XOMultinom_highest_order_statistics", (DL_FUNC) &_XOMultinom_highest_order_statistics, 4},
    {"_XOMultinom_max_order_statistic", (DL_FUNC) &_XOMultinom_max_order_statistic, 3},
    {"_XOMultinom_pmaxmultinom_corrado", (DL_FUNC) &_XOMultinom_pmaxmultinom_corrado, 5},
    {"_XOMultinom_pminmultinom_corrado", (DL_FUNC) &_XOMultinom_pminmultinom_corrado, 5},
    {"_XOMultinom_prangemultinom_corrado", (DL_FUNC) &_XOMultinom_prangemultinom_corrado, 5},
    {"_XOMultinom_range_probability", (DL_FUNC) &_XOMultinom_range_probability, 3},
    {NULL, NULL, 0}
};

RcppExport void R_init_XOMultinom(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
