# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

equi_prob_max_eq <- function(n, m, c) {
    .Call(`_XOMultinom_equi_prob_max_eq`, n, m, c)
}

equi_prob_min_leq <- function(n, m, c) {
    .Call(`_XOMultinom_equi_prob_min_leq`, n, m, c)
}

equi_prob_min_eq <- function(n, m, c) {
    .Call(`_XOMultinom_equi_prob_min_eq`, n, m, c)
}

equi_prob_range_eq <- function(n, m, r) {
    .Call(`_XOMultinom_equi_prob_range_eq`, n, m, r)
}

equi_prob_highest_eq <- function(n, m, r, J) {
    .Call(`_XOMultinom_equi_prob_highest_eq`, n, m, r, J)
}

prob_max_leq <- function(n, pi, c) {
    .Call(`_XOMultinom_prob_max_leq`, n, pi, c)
}

prob_min_geq <- function(n, pi, c) {
    .Call(`_XOMultinom_prob_min_geq`, n, pi, c)
}

prob_max_gt <- function(n, pi, c) {
    .Call(`_XOMultinom_prob_max_gt`, n, pi, c)
}

prob_min_lt <- function(n, pi, c) {
    .Call(`_XOMultinom_prob_min_lt`, n, pi, c)
}

prob_min_leq <- function(n, pi, c) {
    .Call(`_XOMultinom_prob_min_leq`, n, pi, c)
}

prob_joint <- function(n, pi, a, b) {
    .Call(`_XOMultinom_prob_joint`, n, pi, a, b)
}

prob_max_eq <- function(n, pi, c) {
    .Call(`_XOMultinom_prob_max_eq`, n, pi, c)
}

prob_min_eq <- function(n, pi, c) {
    .Call(`_XOMultinom_prob_min_eq`, n, pi, c)
}

pmf_max_range <- function(n, pi, c_lo, c_hi) {
    .Call(`_XOMultinom_pmf_max_range`, n, pi, c_lo, c_hi)
}

pmf_min_range <- function(n, pi, c_lo, c_hi) {
    .Call(`_XOMultinom_pmf_min_range`, n, pi, c_lo, c_hi)
}

prob_range_lt <- function(n, pi, r) {
    .Call(`_XOMultinom_prob_range_lt`, n, pi, r)
}

prob_range_leq <- function(n, pi, r) {
    .Call(`_XOMultinom_prob_range_leq`, n, pi, r)
}

prob_range_geq <- function(n, pi, r) {
    .Call(`_XOMultinom_prob_range_geq`, n, pi, r)
}

prob_range_gt <- function(n, pi, r) {
    .Call(`_XOMultinom_prob_range_gt`, n, pi, r)
}

prob_range_eq <- function(n, pi, r) {
    .Call(`_XOMultinom_prob_range_eq`, n, pi, r)
}

pmf_range_range <- function(n, pi, r_lo, r_hi) {
    .Call(`_XOMultinom_pmf_range_range`, n, pi, r_lo, r_hi)
}

dJlargemultinom_bonetti <- function(x, size, prob, J, logd, verbose) {
    .Call(`_XOMultinom_dJlargemultinom_bonetti`, x, size, prob, J, logd, verbose)
}

dmaxmultinom_bonetti <- function(x, size, prob, logd, verbose) {
    .Call(`_XOMultinom_dmaxmultinom_bonetti`, x, size, prob, logd, verbose)
}

dmaxmultinom_corrado <- function(x, size, prob, logd, verbose) {
    .Call(`_XOMultinom_dmaxmultinom_corrado`, x, size, prob, logd, verbose)
}

dminmultinom_bonetti <- function(x, size, prob, logd, verbose) {
    .Call(`_XOMultinom_dminmultinom_bonetti`, x, size, prob, logd, verbose)
}

dminmultinom_corrado <- function(x, size, prob, logd, verbose) {
    .Call(`_XOMultinom_dminmultinom_corrado`, x, size, prob, logd, verbose)
}

drangemultinom_bonetti <- function(x, size, prob, logd, verbose) {
    .Call(`_XOMultinom_drangemultinom_bonetti`, x, size, prob, logd, verbose)
}

drangemultinom_corrado <- function(x, size, prob, logd, verbose) {
    .Call(`_XOMultinom_drangemultinom_corrado`, x, size, prob, logd, verbose)
}

highest_order_statistics <- function(td, n, m, J) {
    .Call(`_XOMultinom_highest_order_statistics`, td, n, m, J)
}

max_for_min <- function(t_max_d, n, m, t) {
    .Call(`_XOMultinom_max_for_min`, t_max_d, n, m, t)
}

max_for_range <- function(t_max, n, m, prev, t) {
    .Call(`_XOMultinom_max_for_range`, t_max, n, m, prev, t)
}

max_order_statistic <- function(td, n, m) {
    .Call(`_XOMultinom_max_order_statistic`, td, n, m)
}

pJlargemultinom_bonetti <- function(x, size, prob, J, logd, verbose) {
    .Call(`_XOMultinom_pJlargemultinom_bonetti`, x, size, prob, J, logd, verbose)
}

pmaxmultinom_bonetti <- function(x, size, prob, logd, verbose) {
    .Call(`_XOMultinom_pmaxmultinom_bonetti`, x, size, prob, logd, verbose)
}

pmaxmultinom_corrado <- function(x, size, prob, logd, verbose) {
    .Call(`_XOMultinom_pmaxmultinom_corrado`, x, size, prob, logd, verbose)
}

pminmultinom_bonetti <- function(x, size, prob, logd, verbose) {
    .Call(`_XOMultinom_pminmultinom_bonetti`, x, size, prob, logd, verbose)
}

pminmultinom_corrado <- function(x, size, prob, logd, verbose) {
    .Call(`_XOMultinom_pminmultinom_corrado`, x, size, prob, logd, verbose)
}

prangemultinom_bonetti <- function(x, size, prob, logd, verbose) {
    .Call(`_XOMultinom_prangemultinom_bonetti`, x, size, prob, logd, verbose)
}

prangemultinom_corrado <- function(x, size, prob, logd, verbose) {
    .Call(`_XOMultinom_prangemultinom_corrado`, x, size, prob, logd, verbose)
}

range_probability <- function(td, n, m) {
    .Call(`_XOMultinom_range_probability`, td, n, m)
}

recursive_sum <- function(td, n, m, J, sum_depth, cur_depth, rangeArg) {
    .Call(`_XOMultinom_recursive_sum`, td, n, m, J, sum_depth, cur_depth, rangeArg)
}

smallest_order_value <- function(td, n, m) {
    .Call(`_XOMultinom_smallest_order_value`, td, n, m)
}

