# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' CDF of the sum of the first \eqn{J} largest order statistics for a
#' multinomial distribution.
#'
#' This function calculates the cumulative distribution function (CDF) of the
#' sum of the first \eqn{J} largest order statistics under an equiprobable
#' multinomial distribution assumption.
#'
#' @param t A length-one numeric vector indicating the value to compute the CDF
#'   for.
#' @param n A length-one integer vector indicating the number of independent
#'   balls.
#' @param m A length-one integer vector indicating the number of independent
#'   urns/cells.
#' @param J A length-one integer vector indicating the number of largest order
#'   statistics.
#' @return A length-one numeric vector representing the probability of the
#'   sum of the \eqn{J} largest order statistic.
#' @author Sergio Venturini \email{sergio.venturini@unicatt.it}
#' @seealso \code{\link{max_order_statistic}} for computing the
#'   CDF of the maximum.
#' @seealso \code{\link{smallest_order_value}} for computing the CDF
#'   of the smallest order statistic.
#' @seealso \code{\link{range_probability}} for computing the CDF
#'   of the range.
#' @references
#'   Bonetti, M., Cirillo, P., Ogay, A. (2019), "Computing the exact
#'   distributions of some functions of the ordered multinomial counts:
#'   maximum, minimum, range and sums of order statistics", Royal Society
#'   Open Science, 6: 190198, <http://dx.doi.org/10.1098/rsos.190198>.
#' @examples
#' highest_order_statistics_C(6, 10, 5, 2)
#'
highest_order_statistics_C <- function(td, n, m, J) {
    .Call(`_XOMultinom_highest_order_statistics_C`, td, n, m, J)
}

#' Utility function for computing the distribution of the smallest order
#' statistic.
#'
#' This is an auxiliary function to the distribution of the smallest order
#' statistic.
#'
#' @param t_max A length-one numeric vector indicating the value to compute the
#'   survival function for.
#' @param n A length-one integer vector indicating the number of independent
#'   balls.
#' @param m A length-one integer vector indicating the number of independent
#'   urns/cells.
#' @param t A length-one numeric vector indicating the value to compute for.
#' @return A length-one numeric vector.
#' @author Sergio Venturini \email{sergio.venturini@unicatt.it}
#' @seealso \code{\link{highest_order_statistics}} for computing the
#'   CDF of the sum of the first \eqn{J} largest order statistics.
#' @seealso \code{\link{smallest_order_value}} for computing the CDF
#'   of the smallest order statistic.
#' @seealso \code{\link{range_probability}} for computing the CDF
#'   of the range.
#' @references
#'   Bonetti, M., Cirillo, P., Ogay, A. (2019), "Computing the exact
#'   distributions of some functions of the ordered multinomial counts:
#'   maximum, minimum, range and sums of order statistics", Royal Society
#'   Open Science, 6: 190198, <http://dx.doi.org/10.1098/rsos.190198>.
#' @examples
#' smallest_order_value_C(1, 10, 5) # P(N_(1) <= 1; n = 10, m = 5)
#'
max_for_min_C <- function(t_max, n, m, t) {
    .Call(`_XOMultinom_max_for_min_C`, t_max, n, m, t)
}

#' Utility function for computing the distribution of the range.
#'
#' This is an auxiliary function to the distribution of the range.
#'
#' @param t_max A length-one numeric vector indicating the value to compute the
#'   survival function for.
#' @param n A length-one integer vector indicating the number of independent
#'   balls.
#' @param m A length-one integer vector indicating the number of independent
#'   urns/cells.
#' @param prev Integer vector containing the previous iteration values.
#' @param t A length-one numeric vector indicating the value to compute for.
#' @return A length-one numeric vector.
#' @author Sergio Venturini \email{sergio.venturini@unicatt.it}
#' @seealso \code{\link{highest_order_statistics}} for computing the
#'   CDF of the sum of the first \eqn{J} largest order statistics.
#' @seealso \code{\link{smallest_order_value}} for computing the CDF
#'   of the smallest order statistic.
#' @seealso \code{\link{range_probability}} for computing the CDF
#'   of the range.
#' @references
#'   Bonetti, M., Cirillo, P., Ogay, A. (2019), "Computing the exact
#'   distributions of some functions of the ordered multinomial counts:
#'   maximum, minimum, range and sums of order statistics", Royal Society
#'   Open Science, 6: 190198, <http://dx.doi.org/10.1098/rsos.190198>.
#' @examples
#' range_probability_C(1, 7, 10)
#'
max_for_range_C <- function(t_max, n, m, prev, t) {
    .Call(`_XOMultinom_max_for_range_C`, t_max, n, m, prev, t)
}

#' CDF of the highest order statistic for an equiprobable multinomial
#' distribution.
#'
#' This function calculates the cumulative distribution function (CDF) of the
#' highest order statistic (i.e. the maximum) under an equiprobable multinomial
#' distribution assumption.
#'
#' @param td A length-one numeric vector indicating the value to compute the CDF
#'   for.
#' @param n A length-one integer vector indicating the number of independent
#'   balls.
#' @param m A length-one integer vector indicating the number of independent
#'   urns/cells.
#' @return A length-one numeric vector representing the probability of the
#'   highest order statistic.
#' @author Sergio Venturini \email{sergio.venturini@unicatt.it}
#' @seealso \code{\link{highest_order_statistics}} for computing the
#'   CDF of the sum of the first \eqn{J} largest order statistics.
#' @seealso \code{\link{smallest_order_value}} for computing the CDF
#'   of the smallest order statistic.
#' @seealso \code{\link{range_probability}} for computing the CDF
#'   of the range.
#' @references
#'   Bonetti, M., Cirillo, P., Ogay, A. (2019), "Computing the exact
#'   distributions of some functions of the ordered multinomial counts:
#'   maximum, minimum, range and sums of order statistics", Royal Society
#'   Open Science, 6: 190198, <http://dx.doi.org/10.1098/rsos.190198>.
#' @examples
#' max_order_statistic_C(3, 10, 5) # P(N_(m) <= 3; n = 10, m = 5)
#'
max_order_statistic_C <- function(td, n, m) {
    .Call(`_XOMultinom_max_order_statistic_C`, td, n, m)
}

pmaxmultinom_C_one <- function(x, size, prob, verbose, tol) {
    .Call(`_XOMultinom_pmaxmultinom_C_one`, x, size, prob, verbose, tol)
}

pmaxmultinom_C <- function(x, size, prob, logd, verbose, tol) {
    .Call(`_XOMultinom_pmaxmultinom_C`, x, size, prob, logd, verbose, tol)
}

computeQk_max <- function(x, k, size, prob, verbose, tol) {
    .Call(`_XOMultinom_computeQk_max`, x, k, size, prob, verbose, tol)
}

pmaxmultinom_corrado_one <- function(x, size, prob, verbose, tol) {
    .Call(`_XOMultinom_pmaxmultinom_corrado_one`, x, size, prob, verbose, tol)
}

pmaxmultinom_corrado <- function(x, size, prob, logd, verbose, tol) {
    .Call(`_XOMultinom_pmaxmultinom_corrado`, x, size, prob, logd, verbose, tol)
}

pminmultinom_C_one <- function(x, size, prob, verbose, tol) {
    .Call(`_XOMultinom_pminmultinom_C_one`, x, size, prob, verbose, tol)
}

pminmultinom_C <- function(x, size, prob, logd, verbose, tol) {
    .Call(`_XOMultinom_pminmultinom_C`, x, size, prob, logd, verbose, tol)
}

computeQk_min <- function(x, k, size, prob, verbose, tol) {
    .Call(`_XOMultinom_computeQk_min`, x, k, size, prob, verbose, tol)
}

pminmultinom_corrado_one <- function(x, size, prob, verbose, tol) {
    .Call(`_XOMultinom_pminmultinom_corrado_one`, x, size, prob, verbose, tol)
}

pminmultinom_corrado <- function(x, size, prob, logd, verbose, tol) {
    .Call(`_XOMultinom_pminmultinom_corrado`, x, size, prob, logd, verbose, tol)
}

#' CDF of the range for an equiprobable multinomial distribution.
#'
#' This function calculates the cumulative distribution function (CDF)
#' of the range under the assumption of an equiprobable multinomial
#' distribution.
#'
#' @param td A length-one numeric vector indicating the value to compute the
#'   survival function for.
#' @param n A length-one integer vector indicating the number of independent
#'   balls.
#' @param m A length-one integer vector indicating the number of independent
#'   urns/cells.
#' @return A length-one numeric vector representing the probability of the
#'   smallest order statistic.
#' @author Sergio Venturini \email{sergio.venturini@unicatt.it}
#' @seealso \code{\link{highest_order_statistics}} for computing the
#'   CDF of the sum of the first \eqn{J} largest order statistics.
#' @seealso \code{\link{smallest_order_value}} for computing the CDF
#'   of the smallest order statistic.
#' @seealso \code{\link{highest_order_statistics}} for computing the sum of
#'   the first \eqn{J} largest order statistics.
#' @references
#'   Bonetti, M., Cirillo, P., Ogay, A. (2019), "Computing the exact
#'   distributions of some functions of the ordered multinomial counts:
#'   maximum, minimum, range and sums of order statistics", Royal Society
#'   Open Science, 6: 190198, <http://dx.doi.org/10.1098/rsos.190198>.
#' @examples
#' range_probability_C(1, 7, 10)
#'
range_probability_C <- function(td, n, m) {
    .Call(`_XOMultinom_range_probability_C`, td, n, m)
}

#' Utility function for computing recursively a sum.
#'
#' This is an auxiliary function to compute a sum recursively.
#'
#' @param td A length-one numeric vector indicating the value to compute the
#'   function for.
#' @param n A length-one integer vector indicating the number of independent
#'   balls.
#' @param m A length-one integer vector indicating the number of independent
#'   urns/cells.
#' @param J A length-one integer vector indicating the number of largest order
#'   statistics.
#' @param sum_depth A length-one integer vector indicating the summation depth.
#' @param cur_depth A length-one integer vector indicating the current
#'   summation depth.
#' @param rangeArg Integer vector indicating the range of the summation.
#' @return A length-one numeric vector representing the summation value.
#' @author Sergio Venturini \email{sergio.venturini@unicatt.it}
#' @seealso \code{\link{highest_order_statistics}} for computing the CDF
#'   of the sum for the first \eqn{J} largest order statistics for an
#'   equiprobable multinomial distribution.
#' @references
#'   Bonetti, M., Cirillo, P., Ogay, A. (2019), "Computing the exact
#'   distributions of some functions of the ordered multinomial counts:
#'   maximum, minimum, range and sums of order statistics", Royal Society
#'   Open Science, 6: 190198, <http://dx.doi.org/10.1098/rsos.190198>.
#' @examples
#' highest_order_statistics(6, 10, 5, 2)
#'
recursive_sum_C <- function(td, n, m, J, sum_depth, cur_depth, rangeArg) {
    .Call(`_XOMultinom_recursive_sum_C`, td, n, m, J, sum_depth, cur_depth, rangeArg)
}

#' Survival function of the smallest order statistic for an equiprobable
#' multinomial distribution.
#'
#' This function calculates the survival function (i.e. the probability to be
#' greater than or equal to a given value) for the smallest order statistic
#' (i.e. the minimum) under an equiprobable multinomial distribution
#' assumption.
#'
#' @param td A length-one numeric vector indicating the value to compute the
#'   survival function for.
#' @param n A length-one integer vector indicating the number of independent
#'   balls.
#' @param m A length-one integer vector indicating the number of independent
#'   urns/cells.
#' @return A length-one numeric vector representing the probability of the
#'   smallest order statistic.
#' @author Sergio Venturini \email{sergio.venturini@unicatt.it}
#' @seealso \code{\link{highest_order_statistics}} for computing the
#'   CDF of the sum of the first \eqn{J} largest order statistics.
#' @seealso \code{\link{smallest_order_value}} for computing the CDF
#'   of the smallest order statistic.
#' @seealso \code{\link{range_probability}} for computing the CDF
#'   of the range.
#' @references
#'   Bonetti, M., Cirillo, P., Ogay, A. (2019), "Computing the exact
#'   distributions of some functions of the ordered multinomial counts:
#'   maximum, minimum, range and sums of order statistics", Royal Society
#'   Open Science, 6: 190198, <http://dx.doi.org/10.1098/rsos.190198>.
#' @examples
#' smallest_order_value_C(1, 10, 5) # P(N_(1) <= 1; n = 10, m = 5)
#'
smallest_order_value_C <- function(td, n, m) {
    .Call(`_XOMultinom_smallest_order_value_C`, td, n, m)
}

any_sug <- function(x) {
    .Call(`_XOMultinom_any_sug`, x)
}

cumsum_rcpp <- function(x) {
    .Call(`_XOMultinom_cumsum_rcpp`, x)
}

matelmult_rcpp <- function(v1, v2) {
    .Call(`_XOMultinom_matelmult_rcpp`, v1, v2)
}

rev_rcpp <- function(x) {
    .Call(`_XOMultinom_rev_rcpp`, x)
}

aggregate_sum_rcpp <- function(x, by) {
    .Call(`_XOMultinom_aggregate_sum_rcpp`, x, by)
}

list_resize_rcpp <- function(x, newsize) {
    .Call(`_XOMultinom_list_resize_rcpp`, x, newsize)
}

nm2df_rcpp <- function(x) {
    .Call(`_XOMultinom_nm2df_rcpp`, x)
}

df2nm_rcpp <- function(x) {
    .Call(`_XOMultinom_df2nm_rcpp`, x)
}

flipcols_rcpp <- function(x) {
    .Call(`_XOMultinom_flipcols_rcpp`, x)
}

